In [1]:
import numpy as np

In [2]:
np.array([10,20,24,5,15,50])

array([10, 20, 24,  5, 15, 50])

In [4]:
a = np.array([2,34,667,5,31,100,233,1])
a[4]

31

In [5]:
# Mostrando información desde el índe 3 en adelante
a[3:]

array([  5,  31, 100, 233,   1])

In [6]:
# Mostrando información desde el índe 3 hasta la posición 7
a[3:7]

array([  5,  31, 100, 233])

In [9]:
# Mostrando elementos de 3 en 3
a[1::3]

array([34, 31,  1])

In [11]:
# Creando arreglos dinámicos

# iniciando con 5 elementos 
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [12]:
# 2D
# arreglo 2dimensional 
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [15]:
# Arreglo el cual le pasamos como 
# 1ER parámetro: Menor valor.
# 2do parámetro: Valor máximo.
# 3er valor: Cantidad de elementos.

np.linspace(3,10,5)

array([ 3.  ,  4.75,  6.5 ,  8.25, 10.  ])

In [17]:
# Arreglo de 2 dimensiones

b = np.array([['x','y','z'],['a','c','e']])
print(b)
type(b)

[['x' 'y' 'z']
 ['a' 'c' 'e']]


numpy.ndarray

In [18]:
# Examinando las dimensiones de mi arreglo 
b.ndim

2

In [21]:
# Ordenando mi arreglo 
c = [12,4,10,40,2]
np.sort(c)

array([ 2,  4, 10, 12, 40])

In [24]:
# Ordenamiento especificado

headers = [('nombre','S10'), ('edad', int), ('nacionalidad','S100')]
data = [('Amelie',21,'Francesa'), 
         ('Valerie', 30,'Canadiense'),
         ('Valentina',25,'Inglesa'),
         ('Alejandra',22,'Cubana')]
users = np.array(data,dtype=headers)

np.sort(users, order = 'edad')

array([(b'Amelie', 21, b'Francesa'), (b'Alejandra', 22, b'Cubana'),
       (b'Valentina', 25, b'Inglesa'), (b'Valerie', 30, b'Canadiense')],
      dtype=[('nombre', 'S10'), ('edad', '<i8'), ('nacionalidad', 'S100')])

In [25]:
# Nos crea un arreglo desde 0 hasta n-1
np.arange(25)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [26]:
# nos crea un arreglo desde la primera posición hasta la última - 1
np.arange(5,30)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29])

In [27]:
# Le especificamos valor inicial, valor final, como lo iniciaremos
np.arange(5,30,5)

array([ 5, 10, 15, 20, 25])

In [28]:
# Full es para arreglo bidimensional.
np.full((3,5),10)

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [29]:
# Diagonal de una matriz bidimensional.
np.diag([0,3,9,10])

array([[ 0,  0,  0,  0],
       [ 0,  3,  0,  0],
       [ 0,  0,  9,  0],
       [ 0,  0,  0, 10]])